#!/bin/bash

DEBUG=1
JASMINE_DEBUG=1
VELOCITY_DEBUG=1
VELOCITY_DEBUG_MIRROR=1
VELOCITY=1
VELOCITY_CI=1
CUCUMBER=1
JASMINE_SERVER_UNIT=0
JASMINE_SERVER_INTEGRATION=1
JASMINE_CLIENT_UNIT=0
JASMINE_CLIENT_INTEGRATION=0
CHIMP_OPTIONS='--screenshotsOnError=true --jsonOutput=${CIRCLE_TEST_REPORTS}/cucumber/tests.cucumber'
CUCUMBER_SCREENSHOTS_DIR=${CIRCLE_ARTIFACTS}
CUCUMBER_FORMAT=json
meteor --test --settings=settings.json
