webonaut:
  build: .
  ports:
   - "300:80"
  links:
   - webonaut-mongo
  environment:
   - MONGO_URL=mongodb://webonaut-mongo/webonaut
   - ROOT_URL=http://yourapp.com



webonaut-mongo:
  image: mongo:latest
